# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(b'r', b'running'), (b'd', b'done'), (b'e', b'error'), (b'w', b'waitting')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('test', models.CharField(max_length=50)),
                ('testurl', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('devurl', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Svn',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='svn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regression.Svn'),
        ),
    ]
