# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0002_auto_20151208_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='war',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
