# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0003_map_war'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='svn',
        ),
    ]
