# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0005_project_build_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='job_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
