# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0008_auto_20151209_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='build_command',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='dev_revision_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job_tests',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
    ]
