# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0014_auto_20151209_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_tests',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
        migrations.AlterField(
            model_name='map',
            name='war',
            field=models.TextField(blank=True, null=True),
        ),
    ]
