# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0020_auto_20151210_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scm',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_tests',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
    ]
