# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0029_auto_20151214_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_test',
            name='pid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_test',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
    ]
