# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0033_auto_20151214_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('build_command', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[(b'r', b'running'), (b'd', b'done'), (b'e', b'error'), (b'w', b'waiting'), (b'f', b'fail'), (b'p', b'pass')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='status',
            field=models.CharField(choices=[(b'r', b'running'), (b'd', b'done'), (b'e', b'error'), (b'w', b'waiting'), (b'f', b'fail'), (b'p', b'pass')], max_length=20),
        ),
    ]
