# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0035_auto_20151214_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
    ]
