# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0037_auto_20151215_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='log',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_test',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
    ]
