# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0048_auto_20151229_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_test',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
        migrations.AlterField(
            model_name='log',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scm',
            field=models.CharField(choices=[(b'svn', b'svn'), (b'git', b'git')], max_length=10),
        ),
    ]
