# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0049_auto_20160307_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_test',
            name='robot_parameter',
            field=models.CharField(blank=True, default=b'', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
        migrations.AlterField(
            model_name='log',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
        migrations.AlterField(
            model_name='map',
            name='robot_parameter',
            field=models.CharField(blank=True, default=b'', max_length=250, null=True),
        ),
    ]
