# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0051_auto_20160309_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_test',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
        migrations.AlterField(
            model_name='log',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
    ]
