# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0052_auto_20161109_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='dev_revision_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='pid',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='report',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='revision_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_test',
            name='status',
            field=models.CharField(blank=True, choices=[(b'r', b'running'), (b'd', b'done'), (b'e', b'error'), (b'w', b'waiting'), (b'FAIL', b'FAIL'), (b'PASS', b'PASS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regression.Job'),
        ),
    ]
